name: flutter_pdfview_professor
description: A Flutter plugin that provides a PDFView widget on Android.
version: 1.0.0
homepage: https://github.com/shubhamsinha2009/flutter_pdfview_professor

environment:
  sdk: ">=2.16.1 < 3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0  

flutter:
  plugin:
    platforms:
      android:
        package: io.professor.plugins.pdfviewflutter
        pluginClass: PDFViewFlutterPlugin
